# Generated by Django 4.1.7 on 2023-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPcloudCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('lastLogin', models.DateField(blank=True, null=True)),
                ('auth', models.CharField(max_length=400)),
            ],
        ),
    ]
