# Generated by Django 4.1.7 on 2023-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commision', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isSettled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateSettled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('totalConnects', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCommision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commision', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isSettled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('totalConnects', models.PositiveIntegerField()),
            ],
        ),
    ]
