# Generated by Django 4.1.7 on 2023-03-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('affiliate', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatesettled',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.affiliate'),
        ),
        migrations.AddField(
            model_name='affiliateconnection',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.affiliate'),
        ),
        migrations.AddField(
            model_name='affiliateconnection',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='organization.organization'),
        ),
    ]
