# Generated by Django 4.2 on 2023-04-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='proprietor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationtier'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.zone'),
        ),
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.featurecategory'),
        ),
        migrations.AddField(
            model_name='customplan',
            name='features',
            field=models.ManyToManyField(to='organization.feature'),
        ),
    ]
