# Generated by Django 4.2 on 2023-04-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('H', 'Hold'), ('A', 'Active'), ('I', 'In Active')], default='A', max_length=1),
        ),
    ]
