# Generated by Django 4.1.7 on 2023-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('H', 'Hold'), ('A', 'Active'), ('I', 'In Active')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='organizationpcloudcredentials',
            name='lastLogin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
