# Generated by Django 4.1.7 on 2023-03-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationNormalShedule',
            new_name='OrganizationSchedule',
        ),
        migrations.RenameField(
            model_name='organizationschedule',
            old_name='sheduledAt',
            new_name='scheduledAt',
        ),
    ]
