# Generated by Django 4.1.7 on 2023-03-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_rename_organizationnormalshedule_organizationschedule_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturePlan',
            new_name='CustomPlan',
        ),
        migrations.RenameModel(
            old_name='CustomFeaturePlan',
            new_name='Plan',
        ),
        migrations.AddField(
            model_name='organization',
            name='customPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.customplan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'In Active'), ('H', 'Hold')], default='A', max_length=1),
        ),
    ]
