# Generated by Django 4.1.7 on 2023-03-20 17:12

from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_rename_featureplan_customplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='proprietorImageUrl',
        ),
        migrations.AddField(
            model_name='organization',
            name='proprietorImage',
            field=models.ImageField(blank=True, null=True, upload_to=organization.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.plan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('H', 'Hold'), ('A', 'Active'), ('I', 'In Active')], default='A', max_length=1),
        ),
    ]
