# Generated by Django 4.1.7 on 2023-03-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_organization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('I', 'In Active'), ('H', 'Hold'), ('A', 'Active')], default='A', max_length=1),
        ),
    ]
