# Generated by Django 4.1.7 on 2023-03-30 11:41

from django.db import migrations, models
import django.utils.timezone
import event.validators
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_alter_organization_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationecardtemplate',
            old_name='htmlFileName',
            new_name='htmlFile',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='pcloudImageID',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='pcloudPublicCode',
        ),
        migrations.RemoveField(
            model_name='organizationecardtemplate',
            name='pcloudImageID',
        ),
        migrations.RemoveField(
            model_name='organizationecardtemplate',
            name='pcloudPublicCode',
        ),
        migrations.RemoveField(
            model_name='organizationwebpagetemplate',
            name='htmlFileName',
        ),
        migrations.RemoveField(
            model_name='organizationwebpagetemplate',
            name='pcloudImageID',
        ),
        migrations.RemoveField(
            model_name='organizationwebpagetemplate',
            name='pcloudPublicCode',
        ),
        migrations.AddField(
            model_name='organization',
            name='studioLogo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/studiologo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='studioPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='organization/studiophoto'),
        ),
        migrations.AddField(
            model_name='organizationecardtemplate',
            name='templateOverview',
            field=models.ImageField(default=1, upload_to='organizationtemplates/ecardoverview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationecardtemplate',
            name='uploadedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationwebpage',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationwebpagetemplate',
            name='htmlFile',
            field=models.FileField(default=1, upload_to=organization.models.get_file_path, validators=[event.validators.FileValidator(['html'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationwebpagetemplate',
            name='templateOverview',
            field=models.ImageField(default=1, upload_to='organizationtemplates/webtemplateoverview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationwebpagetemplate',
            name='uploadedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('I', 'In Active'), ('A', 'Active'), ('H', 'Hold')], default='A', max_length=1),
        ),
    ]
