# Generated by Django 4.1.7 on 2023-03-30 13:52

from django.db import migrations, models
import event.validators
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_rename_htmlfilename_organizationecardtemplate_htmlfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationwebpage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationwebpage',
            name='template',
        ),
        migrations.AlterField(
            model_name='organization',
            name='facebook',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='instagram',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='youtube',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='organizationecardtemplate',
            name='htmlFile',
            field=models.FileField(upload_to=organization.models.get_ecard_path, validators=[event.validators.FileValidator(['html'])]),
        ),
        migrations.DeleteModel(
            name='OrganizationEcard',
        ),
        migrations.DeleteModel(
            name='OrganizationWebpage',
        ),
    ]
