# Generated by Django 4.1.7 on 2023-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_alter_organization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('H', 'Hold'), ('I', 'In Active'), ('A', 'Active')], default='A', max_length=1),
        ),
    ]
