# Generated by Django 4.1.7 on 2023-03-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_avatar_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('O', 'Other'), ('M', 'Male')], max_length=1),
        ),
    ]
