# Generated by Django 4.2 on 2023-04-10 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMIPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='Due', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emiEnabled', models.BooleanField(default=False)),
                ('tenure', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expireDate', models.DateField()),
            ],
        ),
    ]
