# Generated by Django 4.1.7 on 2023-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('isSelectionEnable', models.BooleanField(default=False)),
                ('isSheetPlacementEnable', models.BooleanField(default=False)),
                ('maxSelectionCount', models.IntegerField(blank=True, null=True)),
                ('isPublic', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcloudImageID', models.CharField(max_length=100)),
                ('pcloudPublicCode', models.CharField(max_length=1000)),
                ('isActive', models.BooleanField(default=True)),
                ('isSelected', models.BooleanField(default=False)),
                ('sheetNumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=1, null=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('faceCharacters', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalInvitationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isWhatsappInvitation', models.BooleanField()),
                ('isMessageInvitation', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DigitalInvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('thumb', models.URLField(blank=True, null=True)),
                ('pcloudImageId', models.CharField(blank=True, max_length=50, null=True)),
                ('pcloudPublicCode', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('quotation', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('venue', models.CharField(max_length=70)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcloudImageID', models.CharField(max_length=100)),
                ('pcloudPublicCode', models.CharField(max_length=1000)),
                ('templateName', models.CharField(max_length=100)),
                ('htmlFileName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EventPaymentRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventWebpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('isPublic', models.BooleanField(default=True)),
                ('passCode', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventWebpageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcloudImageID', models.CharField(max_length=100)),
                ('pcloudPublicCode', models.CharField(max_length=1000)),
                ('templateName', models.CharField(max_length=100)),
                ('htmlFileName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EventWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEventShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('sheduledAt', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TargetedAudient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audientName', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
