# Generated by Django 4.2 on 2023-04-10 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import event.models
import event.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('isSelectionEnable', models.BooleanField(default=False)),
                ('isSheetPlacementEnable', models.BooleanField(default=False)),
                ('maxSelectionCount', models.IntegerField(blank=True, null=True)),
                ('isPublic', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceUrl', models.URLField(max_length=250)),
                ('imageCode', models.IntegerField()),
                ('publicCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcloudImageID', models.CharField(max_length=100)),
                ('pcloudPublicCode', models.CharField(max_length=1000)),
                ('isActive', models.BooleanField(default=True)),
                ('isSelected', models.BooleanField(default=False)),
                ('imageLink', models.URLField(max_length=1638)),
                ('sheetNumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=1, null=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('faceCharacters', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalInvitationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isWhatsappInvitation', models.BooleanField()),
                ('isMessageInvitation', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DigitalInvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateOverview', models.ImageField(upload_to='eventtemplates/digitalinvitationtemplateoverview')),
                ('templateName', models.CharField(max_length=100)),
                ('htmlFile', models.FileField(upload_to=event.models.get_digital_invitation_template_path, validators=[event.validators.FileValidator(['html'])])),
                ('uploadedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('thumb', models.URLField(blank=True, null=True)),
                ('pcloudImageId', models.CharField(blank=True, max_length=50, null=True)),
                ('pcloudPublicCode', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('quotation', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('securityKey', models.IntegerField(default=event.models.generate_unique_digit, unique=True)),
                ('venue', models.CharField(max_length=70)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('passCode', models.CharField(default=event.models.generate_unique_string_invitation, max_length=8, unique=True)),
                ('birthday_person_name', models.CharField(blank=True, max_length=250, null=True)),
                ('groom_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bride_name', models.CharField(blank=True, max_length=250, null=True)),
                ('heroImage1', models.URLField(max_length=500)),
                ('heroImage2', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage3', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage4', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage5', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage6', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage7', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateOverview', models.ImageField(upload_to='eventtemplates/invitationtemplateoverview')),
                ('templateName', models.CharField(max_length=100)),
                ('htmlFile', models.FileField(upload_to=event.models.get_invitation_template_path, validators=[event.validators.FileValidator(['html'])])),
                ('uploadedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventPaymentRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventWebpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('isPublic', models.BooleanField(default=True)),
                ('passCode', models.CharField(default=event.models.generate_unique_string, max_length=8, unique=True)),
                ('heroImage1', models.URLField(max_length=500)),
                ('heroImage2', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage3', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage4', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventWebpageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateOverview', models.ImageField(upload_to='eventtemplates/webtemplateoverview')),
                ('templateName', models.CharField(max_length=100)),
                ('htmlFile', models.FileField(upload_to=event.models.get_file_path, validators=[event.validators.FileValidator(['html'])])),
                ('uploadedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=2000)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetedAudient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audientName', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('isEventDate', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduleAt', models.DateField()),
                ('scheduleTime', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
