# Generated by Django 4.2 on 2023-04-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('organization', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationeventschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='eventwish',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='eventwebpage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webpage', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventwebpage',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.music'),
        ),
        migrations.AddField(
            model_name='eventwebpage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template', to='event.eventwebpagetemplate'),
        ),
        migrations.AddField(
            model_name='eventtransaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventtransaction',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.transactionmode'),
        ),
        migrations.AddField(
            model_name='eventstream',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='eventpaymentremainder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentremainder', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organization.organizationeventcategory'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.music'),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.eventinvitationtemplate'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationeventcategory'),
        ),
    ]
