# Generated by Django 4.1.7 on 2023-03-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_status'),
        ('event', '0004_organizationeventshedule_iseventdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('isEventDate', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('ScheduleAt', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizationEventShedule',
        ),
    ]
