# Generated by Django 4.2 on 2023-04-05 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_organizationeventschedule_scheduleat'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationeventschedule',
            name='scheduleTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
