# Generated by Django 4.1.7 on 2023-03-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_organizationeventschedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationeventschedule',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationeventschedule',
            old_name='ScheduleAt',
            new_name='scheduleAt',
        ),
    ]
