# Generated by Django 4.1.7 on 2023-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_organization_organizationeventschedule_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='imageLink',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
