# Generated by Django 4.1.7 on 2023-03-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_albumimage_imagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_url', models.URLField(max_length=250)),
                ('imageCode', models.IntegerField()),
                ('publicCode', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.album')),
            ],
        ),
    ]
