# Generated by Django 4.1.7 on 2023-03-25 08:21

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_face_url_albumface_faceurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventwebpagetemplate',
            name='htmlFileName',
        ),
        migrations.RemoveField(
            model_name='eventwebpagetemplate',
            name='pcloudImageID',
        ),
        migrations.RemoveField(
            model_name='eventwebpagetemplate',
            name='pcloudPublicCode',
        ),
        migrations.AddField(
            model_name='eventwebpagetemplate',
            name='htmlFile',
            field=models.FileField(default=1, upload_to=event.models.get_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventwebpagetemplate',
            name='templateOverview',
            field=models.ImageField(default=1, upload_to='webtemplateoverview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumface',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='event.album'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='event.album'),
        ),
    ]
