# Generated by Django 4.1.7 on 2023-03-25 08:47

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_eventwebpagetemplate_htmlfilename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinvitationtemplate',
            name='htmlFileName',
        ),
        migrations.RemoveField(
            model_name='eventinvitationtemplate',
            name='pcloudImageID',
        ),
        migrations.RemoveField(
            model_name='eventinvitationtemplate',
            name='pcloudPublicCode',
        ),
        migrations.AddField(
            model_name='eventinvitationtemplate',
            name='htmlFile',
            field=models.FileField(default=1, upload_to=event.models.get_invitation_template_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventinvitationtemplate',
            name='templateOverview',
            field=models.ImageField(default=1, upload_to='webtemplateoverview'),
            preserve_default=False,
        ),
    ]
