# Generated by Django 4.1.7 on 2023-03-25 10:19

from django.db import migrations, models
import django.utils.timezone
import event.models
import event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_digitalinvitationtemplate_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalinvitationtemplate',
            name='uploadedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventinvitationtemplate',
            name='uploadedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventwebpagetemplate',
            name='uploadedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='digitalinvitationtemplate',
            name='htmlFile',
            field=models.FileField(upload_to=event.models.get_digital_invitation_template_path, validators=[event.validators.FileValidator(['html'])]),
        ),
        migrations.AlterField(
            model_name='eventinvitationtemplate',
            name='htmlFile',
            field=models.FileField(upload_to=event.models.get_invitation_template_path, validators=[event.validators.FileValidator(['html'])]),
        ),
        migrations.AlterField(
            model_name='eventwebpagetemplate',
            name='htmlFile',
            field=models.FileField(upload_to=event.models.get_file_path, validators=[event.validators.FileValidator(['html'])]),
        ),
    ]
