# Generated by Django 4.1.7 on 2023-03-26 18:21

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_digitalinvitationtemplate_uploadedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album', to='event.event'),
        ),
        migrations.AlterField(
            model_name='digitalinvitation',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='event.digitalinvitationlog'),
        ),
        migrations.AlterField(
            model_name='eventpaymentremainder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentremainder', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventtransaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventwebpage',
            name='passCode',
            field=models.IntegerField(default=event.models.generate_unique_string, unique=True),
        ),
    ]
