# Generated by Django 4.1.7 on 2023-03-26 18:30

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminpcloudcredential'),
        ('event', '0015_alter_event_mutuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mutuals',
            field=models.ManyToManyField(blank=True, related_name='mutualEvents', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='eventwebpage',
            name='passCode',
            field=models.CharField(default=event.models.generate_unique_string, max_length=8, unique=True),
        ),
    ]
