# Generated by Django 4.1.7 on 2023-03-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_event_mutuals_alter_eventwebpage_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventwebpage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webpage', to='event.event'),
        ),
    ]
