# Generated by Django 4.1.7 on 2023-03-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_time_eventinvitation_birthday_person_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventInvitation',
        ),
    ]
