# Generated by Django 4.1.7 on 2023-03-30 08:18

from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_avatar_gender'),
        ('organization', '0025_alter_organization_status'),
        ('event', '0019_delete_eventinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('passCode', models.CharField(default=event.models.generate_unique_string_invitation, max_length=8, unique=True)),
                ('birthday_person_name', models.CharField(blank=True, max_length=250, null=True)),
                ('groom_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bride_name', models.CharField(blank=True, max_length=250, null=True)),
                ('heroImage1', models.URLField(max_length=500)),
                ('heroImage2', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage3', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage4', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage5', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage6', models.URLField(blank=True, max_length=500, null=True)),
                ('heroImage7', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organization.organizationeventcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.music')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.eventinvitationtemplate')),
            ],
        ),
    ]
