# Generated by Django 4.1.7 on 2023-03-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='event.album'),
        ),
        migrations.AlterField(
            model_name='eventinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='event.event'),
        ),
    ]
