# Generated by Django 4.1.7 on 2023-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_albumimage_album_alter_eventinvitation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='imageLink',
            field=models.URLField(max_length=1638),
        ),
    ]
